apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keyur-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-service
  labels:
    app: orchestrator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator-service
  template:
    metadata:
      labels:
        app: orchestrator-service
    spec:
      containers:
        - name: orchestrator-service
          image: us-east1-docker.pkg.dev/cloud-assignment-k8s/application/orchestrator-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: myvolume
              mountPath: /Keyur_PV_dir
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: keyur-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
spec:
  selector:
    app: orchestrator-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
